### ISSUE TITLE
Storage local metadata [that rarely changes]

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#18]
We need a way to store some meta data that hardly changes. At the moment it is a table with several columns:

- `route_id` = numeric route identifier that is used internally by RTEC
- `route_name_concise` = human-readable concise route name, like `30` or `3A`
- `route_name_long` = something like `30 - Airport - Center`
- `route_osm_relation` = route identifier on OpenStreetMaps, which is used for retrieving a list of segments that make the route, as well as a list of stations; it is a number like `8649765`

1. What is the best way to store this? (CSV, JSON, or hardcode it into a separate file)
2. `route_name_long` might need to be subjected to localization too (so perhaps keeping these strings values in the code itself might be good, because it will give us l10n for free, now that we have the mechanism in place.

**Comment by roata** [comment]
@iamandrewluca, are you ok with the current structure and format in `src/data`? Or is there a better practice?

**Comment by iamandrewluca** [comment]
Yes. First I thought that maybe static data should be placed in `public` folder. But issue will arise when the data will be changed, because name of files is never changed and browser will cache them. Putting the data into `src` folder forces us to use static `import data from './data/...` or dynamic `import('./data...')` And this will prepare data files with a hash in their name, and whenever content of the files is changed a new hash will be generated, so browser cache will be invalidated.

**Comment by roata** [comment]
Alright - the CSVs are in `src/data`, and there's a readme that explains the file structure, so I am closing this.
